name = "security-testing-endpoint"
compatibility_date = "2024-05-15"
pages_build_output_dir = "public"

[[kv_namespaces]]
binding = "SECURITY_LOGS"
id = "998003af96674ee091173a321a99141f"
preview_id = "e46e3d2cac024efa8427600e09f54d2e"
